export interface OutputFormat {
  label: string
  filename: string
  tool: string
}

export const OUTPUT_FORMATS: OutputFormat[] = [
  { label: 'AGENT.md', filename: 'AGENT.md', tool: 'Kiro' },
  { label: 'CLAUDE.md', filename: 'CLAUDE.md', tool: 'Claude Code' },
  { label: '.cursorrules', filename: '.cursorrules', tool: 'Cursor' },
  { label: '.windsurfrules', filename: '.windsurfrules', tool: 'Windsurf' },
  { label: 'copilot-instructions.md', filename: 'copilot-instructions.md', tool: 'GitHub Copilot' },
]

export function generateCursorMdc(projectName: string, techStack: string, content: string): string {
  return `---
description: Core guidelines and architecture rules for the ${projectName} workspace (${techStack})
globs: ["**/*"]
alwaysApply: true
---

${content}
`;
}

export function generateClaudeSettings(answers: Record<string, unknown>): string {
  const stackStr = String(answers['tech_stack'] || '').toLowerCase();

  let linter = "npm run lint";
  let testRunner = "npm run test";

  if (stackStr.includes('python')) {
    linter = "flake8 .";
    testRunner = "pytest";
  } else if (stackStr.includes('rust')) {
    linter = "cargo clippy";
    testRunner = "cargo test";
  } else if (stackStr.includes('go')) {
    linter = "golangci-lint run";
    testRunner = "go test ./...";
  }

  const settings = {
    model: "claude-3-7-sonnet",
    autoApprove: {
      readFiles: true,
      writeFiles: false,
      runCommands: false
    },
    preferredTools: {
      linter,
      testRunner
    }
  };

  return JSON.stringify(settings, null, 2);
}

export function generateSetupScript(
  projectName: string,
  techStack: string,
  content: string,
  claudeSettings: string,
  roadmapContent?: string,
  promptsContent?: string,
): string {
  let script = `#!/bin/bash
# ==============================================================================
# ${projectName} — AI Copilot Workspace Setup
# Auto-generated by agent-md-generator (https://agent-md-generator.edwinfom.dev)
# ==============================================================================

set -e

echo "[INFO] Starting AI Agent configuration setup for '${projectName}'..."

# 1. Create target directories
echo "[INFO] Creating workspace directories..."
mkdir -p .cursor/rules
mkdir -p .claude

# 2. Write AGENT.md (Universal Context)
echo "[INFO] Writing AGENT.md (Universal AI Context)..."
cat << 'AGENT_EOF' > AGENT.md
${content}
AGENT_EOF

# 3. Write CLAUDE.md (Claude Code project conventions)
echo "[INFO] Writing CLAUDE.md (Claude Code Instructions)..."
cp AGENT.md CLAUDE.md

# 4. Write Cursor Rule (.mdc format)
echo "[INFO] Writing .cursor/rules/web-agent.mdc..."
cat << 'CURSOR_EOF' > .cursor/rules/web-agent.mdc
---
description: Core guidelines and architecture rules for the ${projectName} workspace (${techStack})
globs: ["**/*"]
alwaysApply: true
---

${content}
CURSOR_EOF

# 5. Write Claude settings
echo "[INFO] Writing .claude/settings.json..."
cat << 'CLAUDE_EOF' > .claude/settings.json
${claudeSettings}
CLAUDE_EOF
`

  if (roadmapContent) {
    script += `
# 6. Write ROADMAP.md
echo "[INFO] Writing ROADMAP.md (Technical Project Roadmap)..."
cat << 'ROADMAP_EOF' > ROADMAP.md
${roadmapContent}
ROADMAP_EOF
`
  }

  if (promptsContent) {
    script += `
# 7. Write PROMPTS.md
echo "[INFO] Writing PROMPTS.md (AI Prompt Blueprints)..."
cat << 'PROMPTS_EOF' > PROMPTS.md
${promptsContent}
PROMPTS_EOF
`
  }

  script += `
echo "----------------------------------------------------------------------"
echo "[SUCCESS] Setup complete! Your project is optimized for:"
echo "   - Kiro (via AGENT.md)"
echo "   - Claude Code CLI (via CLAUDE.md and .claude/settings.json)"
echo "   - Cursor Composer (via .cursor/rules/web-agent.mdc)"
`

  if (roadmapContent) {
    script += `echo "   - Step-by-Step execution (via ROADMAP.md)"\n`
  }
  if (promptsContent) {
    script += `echo "   - Session-optimized prompting (via PROMPTS.md)"\n`
  }

  script += `echo "----------------------------------------------------------------------"\n`

  return script
}
